//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSR2016_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deals
    {
        public int IdDeal { get; set; }
        public int IdRunner { get; set; }
        public string IdRaceJitOption { get; set; }
    
        public virtual RaceKitOption RaceKitOption { get; set; }
        public virtual Runner Runner { get; set; }
    }
}
