//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSR2016_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsRaceKitOption
    {
        public int id { get; set; }
        public int IdProduct { get; set; }
        public string IdRaceKitOption { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual RaceKitOption RaceKitOption { get; set; }
    }
}
